title: computer.mads-hartmann.com
email: hello@mads-hartmann.com
description: My computer
baseurl: ""
url: "https://computer.mads-hartmann.com"
permalink: pretty

plugins:
  - jekyll-toc
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Serving
detach: false
port: 4000
host: 0.0.0.0
baseurl: "" # does not include hostname
show_dir_listing: false

# Config for jekyll-toc
toc:
  # I don't want the title in the toc
  min_level: 2
