services:
  jekyll:
    name: Jekyll serve
    commands:
      start: |
        cd sites/blog.mads-hartmann.com
        bundle exec jekyll serve --watch --drafts --source src
tasks:
  bundle-install:
    name: Bundle install
    command: |
      cd sites/blog.mads-hartmann.com
      bundle install
    triggeredBy:
      - postDevcontainerStart
      - manual
