source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll", "~> 4.3.3"
gem "jekyll-seo-tag", "~> 2.6"
gem 'jekyll-sitemap', "~> 1.4.0"
gem 'jekyll-feed', "~> 0.15.0"

gem "webrick", "~> 1.7"

# Native protobuf builds invoke rake on Ruby 3.3.
gem "rake", "~> 13.0"
