source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll", "~> 4.3.2"
gem "jekyll-seo-tag", "~> 2.8.0"
gem 'jekyll-sitemap', "~> 1.4.0"
gem 'jekyll-feed', "~> 0.17.0"

gem "webrick", "~> 1.7.0"
