name: mads-hartmann.com
on:
  workflow_dispatch:
  push:
    paths:
      - "sites/mads-hartmann.com/**"
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Upload to S3 (mads-hartmann.com)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --region eu-central-1 --acl public-read sites/mads-hartmann.com/src/ s3://mads-hartmann.com/
          aws cloudfront create-invalidation --region us-east-1 --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'